# Generated by Django 5.1.2 on 2025-04-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_analysisresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresult",
            name="label",
            field=models.CharField(
                choices=[("healthy", "Healthy"), ("covid", "COVID")], max_length=12
            ),
        ),
    ]
