# Generated by Django 5.1.2 on 2025-04-21 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_analysisresult_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresult",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this result was recorded",
            ),
        ),
    ]
