# Generated by Django 5.1.2 on 2025-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_analysisresult_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="breathing_difficulty",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="energy_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="fever",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="sore_throat",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="symptoms",
            field=models.JSONField(default=dict),
        ),
    ]
