# Generated by Django 5.1.2 on 2025-04-01 16:56

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_users_first_name_alter_users_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "MALE"),
                    ("FEMALE", "FEMALE"),
                    ("NON-BINARY", "NON-BINARY"),
                    ("PREFER NOT TO SAY", "PREFER NOT TO SAY"),
                ],
                max_length=17,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AudioRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=users.models.user_audio_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
