# Generated by Django 5.1.2 on 2025-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_analysisresult_audio_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisresult",
            name="audio_file",
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="audio_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
