# Generated by Django 5.1.2 on 2025-04-02 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_users_gender_audiorecording"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AudioRecording",
            new_name="AudioFile",
        ),
    ]
