# Generated by Django 5.1.2 on 2025-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_audiorecording_audiofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
